import type { FirecrawlConfig, FirecrawlExtract } from "./types.js";
import {
  FIRECRAWL_EXTRACT_SCHEMA,
  FIRECRAWL_EXTRACT_PROMPT,
} from "./constants.js";

async function firecrawlScrapeJson(
  url: string,
  config: FirecrawlConfig,
  timeoutMs: number,
): Promise<FirecrawlExtract | null> {
  const response = await fetch(`${config.baseUrl}/v1/scrape`, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${config.apiKey}`,
    },
    body: JSON.stringify({
      url,
      formats: ["json", "markdown"],
      jsonOptions: {
        schema: FIRECRAWL_EXTRACT_SCHEMA,
        prompt: FIRECRAWL_EXTRACT_PROMPT,
      },
      timeout: Math.min(timeoutMs, 90000),
      waitFor: 0, // Adapter handles all waiting (smart 3-phase wait)
    }),
    signal: AbortSignal.timeout(timeoutMs),
  });

  if (!response.ok) return null;

  const body = (await response.json()) as Record<string, unknown>;
  if (!body["success"]) return null;

  const data = body["data"] as Record<string, unknown> | undefined;
  if (!data) return null;

  // Reject non-2xx pages (403 Cloudflare, 404 not found)
  const metadata = data["metadata"] as Record<string, unknown> | undefined;
  const statusCode = metadata?.["statusCode"] as number | undefined;
  if (statusCode && statusCode >= 400) return null;

  // Reject empty/tiny content (page didn't render)
  const markdown = ((data["markdown"] as string) ?? "").trim();
  if (markdown.length < 50) return null;

  // Reject known bot-challenge pages with 200 status
  const BLOCKED_PATTERNS = [
    // Cloudflare
    "just a moment", "checking your browser", "ray id", "cloudflare",
    "cf-browser-verification", "challenge-platform",
    "cf_chl_opt", "managed_checking_msg", "challenge-error-title",
    // Akamai / PerimeterX / DataDome
    "access denied", "reference #", "automated access",
    "request could not be satisfied", "generated by wordfence",
    "px-captcha", "datadome",
    // Generic bot detection
    "enable javascript", "please verify you are a human",
    "captcha", "bot detection", "are you a robot",
    "browser verification", "security check", "human verification",
    // Incapsula / Imperva
    "incapsula incident", "request unsuccessful",
    // DistilNetworks
    "pardon our interruption",
  ];
  const lower = markdown.toLowerCase();
  if (markdown.length < 1500 && BLOCKED_PATTERNS.some((p) => lower.includes(p)))
    return null;

  return ((data["json"] ?? data["extract"] ?? null) as FirecrawlExtract | null);
}

export async function firecrawlExtractAsync(
  urls: string[],
  config: FirecrawlConfig,
  timeoutMs: number,
): Promise<FirecrawlExtract[] | null> {
  try {
    const results: FirecrawlExtract[] = [];
    for (const url of urls) {
      const extract = await firecrawlScrapeJson(url, config, timeoutMs);
      if (extract) results.push(extract);
    }
    return results.length > 0 ? results : null;
  } catch {
    return null;
  }
}
